title: make-crumble-sparkle-creature
hero_image: images/banner.png
description: make-crumble-sparkle-creature description
version: 4
listed: false
copyedit: false
last_tested: "2019-05-01"
steps:
  - title: Introduction
  - title: Making your creature
  - title: Connecting the Sparkles
  - title: Coding two Sparkles
  - title: Colour sequences
  - title: Two Sparkle sequencing
  - title: "Challenge: follow me colour sequence"
    challenge: true
