title: make-crumble-sparkle-creature
hero_image: images/banner.png
description: make-crumble-sparkle-creature description
version: 4
listed: false
copyedit: false
last_tested: "2019-05-01"
steps:
  - title: Introduction
  - title: Making your creature
  - title: Connecting the Sparkles
  - title: Coding two Sparkles
  - title: Coding Sparkle colours using RGB values
  - title: Colour sequence 1 - Sparkle 0
  - title: Colour sequence 2 - both Sparkles
  - title: "Challenge: Follow me light sequence"
    challenge: true
  - title: Colour sequence 3 - random Sparkles intervals
  - title: Colour sequence 4 - random Sparkles colours
  - title: 11
